# name: cuda
channels:
  - nvidia
  - anaconda
  - conda-forge
  # - hcc
dependencies:
  # - beakerx
  - pip
  - python=3.7
  - ipython
  - cxx-compiler
  - jupyter
  - jupyterlab=2.2.0
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - opencv
  - jupyterlab_widgets
  - cudatoolkit-dev=10
  - cudnn=7.6
  - bazel=3.7
  - cupti
  - gcc_linux-64=7.3
  - nvcc_linux-64
  - nccl
  - cmake
  - nvidia-ml
  # - cuda-tools
  # - cudatoolkit
  # - tensorflow-gpu
  # - jupyterlab-extensions
  - nodejs
  # - cuda-driver
  - pip:
    - jupyterlab-git
    - -r file:requirements.txt
# jupyterlab_play_cell_button
# jlab-enhanced-cell-toolbar
# imjoy-jupyter-extension